version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - model-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_APP: ${FLASK_APP}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - .:/src/app/
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - model-api
volumes:
  data:
    driver: local
networks:
  model-api:
    external:
      name: model-api